"""empty message

Revision ID: dda1c08df523
Revises: 
Create Date: 2021-04-25 06:01:54.187763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda1c08df523'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_userid', sa.Integer(), nullable=False),
    sa.Column('other_userid', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=325), nullable=False),
    sa.ForeignKeyConstraint(['origin_userid'], ['user.id'], ),
    sa.ForeignKeyConstraint(['other_userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_message')
    # ### end Alembic commands ###
